### PR TITLE
commiting reg page

### PR DESCRIPTION
**Pull request by Parthasarathi-P**
seeking for approval

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
retype password for confirmation is missing. please do that implement.
image

**Comment by Parthasarathi-P** [comment]
changes done

**Comment by Parthasarathi-P** [comment]
closing

**Comment by Partha-2000-Snp** [comment]
merge is pending so reopening

**Review by ghost — APPROVED** [review]

**Comment by Partha-2000-Snp** [comment]
closing

**Pull request merged**
